# Generated by Django 3.0.1 on 2019-12-30 21:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pastebin_app', '0002_comment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['date'], 'verbose_name': 'comment'},
        ),
        migrations.AddField(
            model_name='comment',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Posted date'),
        ),
        migrations.AddField(
            model_name='comment',
            name='id_paste',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
