# Generated by Django 3.0.1 on 2019-12-31 12:24

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('pastebin_app', '0003_auto_20191230_2227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 31, 12, 24, 22, 320764, tzinfo=utc), verbose_name='Posted date'),
        ),
        migrations.AlterField(
            model_name='paste',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 31, 12, 24, 22, 318763, tzinfo=utc), verbose_name='Creation date'),
        ),
    ]
